"""Scene + per-enemy physical descriptions on encounters: generated by the LLM
(required — the repair loop demands them), persisted in the encounter JSON, served
by the detail API, and round-tripped untouched by the editor's save payload. They
exist to feed the upcoming image-generation and narration systems."""

from __future__ import annotations

import json

import pytest

from ltg_game_server import content, llm

_SCENE = "A drowned library at low tide: shelves furred with kelp, drifting pages."


# One ROLE per body. Generation enforces the §D14 kit floor (two components
# each) AND the anti-sameness gate (no two enemies sharing a kit, four distinct
# archetypes, more than one row and reach), so the fixture pool has to be a real
# pool — four copies of one statline is exactly what those checks reject.
_ROLES = {
    "wader": ("front", "melee", [
        {"id": "jab", "archetype": "Burst", "timing": "proactive",
         "priority": 30, "cooldown": 2, "target_rule": "valuation",
         "telegraph": "Jab — deal 3",
         "verbs": [{"kind": "deal_damage", "amount": 3,
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
        # Wound, not damage, so the kit stays distinct from the shared
        # factory's brute (the sameness gate compares verb SHAPES).
        {"id": "riposte", "archetype": "Punish", "timing": "reactive",
         "trigger": "on_hit", "cooldown": 2, "priority": 25,
         "target_rule": "trigger_source", "telegraph": "Riposte — wound -1/-1",
         "verbs": [{"kind": "wound", "power": 1, "toughness": 1,
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
    ]),
    "archivist": ("rear", "ranged", [
        {"id": "hush", "archetype": "Debilitate", "timing": "proactive",
         "priority": 30, "cooldown": 3, "target_rule": "highest_threat",
         "telegraph": "Hush — stun a hero",
         "verbs": [{"kind": "stun",
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
        {"id": "page_cut", "archetype": "Burst", "timing": "proactive",
         "priority": 40, "cooldown": 2, "target_rule": "valuation",
         "telegraph": "Page-Cut — deal 2",
         "verbs": [{"kind": "deal_damage", "amount": 2,
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
    ]),
    "pale_eel": ("mid", "ranged", [
        {"id": "coil", "archetype": "Escalate", "timing": "proactive",
         "priority": 40, "cooldown": 2, "target_rule": "self",
         "telegraph": "Coil — +1/+1",
         "verbs": [{"kind": "counters", "power": 1, "toughness": 1,
                    "target": {"mode": "self"}}]},
        {"id": "lash", "archetype": "Burst", "timing": "proactive",
         "priority": 30, "cooldown": 2, "target_rule": "channeling_player",
         "telegraph": "Lash — deal 3",
         "verbs": [{"kind": "deal_damage", "amount": 3,
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
    ]),
    "tomekeeper": ("rear", "ranged", [
        {"id": "mend", "archetype": "Fortify", "timing": "proactive",
         "priority": 20, "cooldown": 2, "target_rule": "lowest_hp_ally",
         "telegraph": "Mend — heal an ally 4",
         "verbs": [{"kind": "heal", "amount": 4,
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
        {"id": "ink_spit", "archetype": "Burst", "timing": "proactive",
         "priority": 35, "cooldown": 2, "target_rule": "valuation",
         "telegraph": "Ink-Spit — deal 2",
         "verbs": [{"kind": "deal_damage", "amount": 2,
                    "target": {"mode": "chosen", "side": "ally", "targeted": True}}]},
    ]),
}


def _enemy(eid, desc="A drowned scholar in rotted robes, lantern-eyed."):
    row, mode, comps = _ROLES[eid]
    return {"id": eid, "name": eid.title(), "hp": 8, "power": 2, "level": 2,
            "row": row, "attack_mode": mode,
            "flavor": "hits things", "description": desc,
            "types": ["undead"], "classes": ["warrior"],         # §D21 gate
            "components": [dict(c) for c in comps]}


def _encounter(name="Scene Test Zzz", scene=_SCENE, desc=True):
    # Rounded out to 8 designs by the shared factory: generation now demands
    # 2x-distinct layouts (the beta-playtest variety floor), not just 2x bodies.
    from tests.conftest import gate_clean_pool
    enc = gate_clean_pool(
        [_enemy("wader", desc and "A brine-bloated hulk trailing nets." or ""),
         _enemy("archivist"), _enemy("pale_eel"), _enemy("tomekeeper")],
        name=name)
    enc["scene"] = scene
    for e in enc["enemies"]:
        e.setdefault("description", "A drowned scholar in rotted robes, lantern-eyed.")
        e.setdefault("types", ["undead"])
        e.setdefault("classes", ["wizard"])
    return enc


# --------------------------------------------------------------------------- #
# Persistence + API
# --------------------------------------------------------------------------- #
def test_scene_and_descriptions_persist_and_serve():
    meta = content.save_encounter(_encounter())
    path = content.CONTENT_DIR / f"{meta['id']}.json"
    try:
        on_disk = json.loads(path.read_text())
        assert on_disk["scene"] == _SCENE
        assert all(e["description"] for e in on_disk["enemies"])
        detail = content.encounter_detail(meta["id"])
        assert detail["scene"] == _SCENE
        assert detail["enemies"][1]["description"].startswith("A drowned scholar")
    finally:
        path.unlink(missing_ok=True)


def test_editor_shaped_save_round_trips_scene():
    """The editor posts {name, scene, enemies, tokens} with enemies spread from the
    loaded detail — scene and descriptions must survive an edit-save cycle."""
    meta = content.save_encounter(_encounter())
    path = content.CONTENT_DIR / f"{meta['id']}.json"
    try:
        detail = content.encounter_detail(meta["id"])
        edited = {"name": detail["name"], "scene": detail.get("scene", ""),
                  "enemies": [dict(e, hp=e["hp"] + 1) for e in detail["enemies"]],
                  "tokens": detail["tokens"]}
        content.save_encounter(edited, meta["id"])
        after = content.encounter_detail(meta["id"])
        assert after["scene"] == _SCENE
        assert all(e.get("description") for e in after["enemies"])
        assert after["enemies"][0]["hp"] == 9
    finally:
        path.unlink(missing_ok=True)


def test_hand_authored_encounters_default_to_empty_scene():
    detail = content.encounter_detail("builtin_a")
    assert detail["scene"] == ""


# --------------------------------------------------------------------------- #
# Generation: required, repaired when missing
# --------------------------------------------------------------------------- #
def test_generation_repairs_missing_scene_and_descriptions(monkeypatch):
    incomplete = _encounter(scene="")                      # no scene …
    incomplete["enemies"][2].pop("description")            # … one look missing
    complete = _encounter(name="Scene Repaired Zzz")
    replies = [json.dumps(incomplete), json.dumps(complete)]
    calls = []

    def fake_chat(api_key, model, messages, **kw):
        calls.append(messages[-1]["content"])
        return replies[len(calls) - 1]

    monkeypatch.setattr(llm, "_chat", fake_chat)
    monkeypatch.setattr(llm, "load_settings",
                        lambda: {**llm._default_settings(), "api_key": "sk"})
    meta = llm.generate_encounter(["soren", "ys"], "standard", "")
    path = content.CONTENT_DIR / f"{meta['id']}.json"
    try:
        assert len(calls) == 2                             # rejected, then repaired
        assert '"scene"' in calls[1] and '"description"' in calls[1]
        on_disk = json.loads(path.read_text())
        assert on_disk["scene"] and all(e["description"] for e in on_disk["enemies"])
    finally:
        path.unlink(missing_ok=True)


def test_prompt_teaches_scene_and_descriptions():
    D = llm.DEFAULT_INSTRUCTIONS
    for needle in ('"scene"', '"description"', "Scene & visual descriptions",
                   "battle backdrop", "physical appearance"):
        assert needle in D, needle
    # Every gold example models the pattern.
    assert D.count('"scene":"') == 3
    assert D.count('"description":"') >= 10