"""Scene + per-enemy physical descriptions on encounters: generated by the LLM
(required — the repair loop demands them), persisted in the encounter JSON, served
by the detail API, and round-tripped untouched by the editor's save payload. They
exist to feed the upcoming image-generation and narration systems."""

from __future__ import annotations

import json

import pytest

from ltg_game_server import content, llm

_SCENE = "A drowned library at low tide: shelves furred with kelp, drifting pages."


def _enemy(eid, desc="A drowned scholar in rotted robes, lantern-eyed."):
    # Two components per enemy: generation now enforces the §D14 kit floor
    # (every enemy needs at least two components).
    return {"id": eid, "name": eid.title(), "hp": 8, "power": 2, "level": 2,
            "row": "front", "attack_mode": "melee",
            "flavor": "hits things", "description": desc,
            "components": [
                {"id": "jab", "archetype": "Burst", "timing": "proactive",
                 "priority": 30, "cooldown": 2, "target_rule": "valuation",
                 "telegraph": "Jab — deal 3",
                 "verbs": [{"kind": "deal_damage", "amount": 3,
                            "target": {"mode": "chosen", "side": "ally",
                                       "targeted": True}}]},
                {"id": "riposte", "archetype": "Punish", "timing": "reactive",
                 "trigger": "on_hit", "cooldown": 2, "priority": 25,
                 "target_rule": "trigger_source",
                 "telegraph": "Riposte — deal 2",
                 "verbs": [{"kind": "deal_damage", "amount": 2,
                            "target": {"mode": "chosen", "side": "ally",
                                       "targeted": True}}]},
            ]}


def _encounter(name="Scene Test Zzz", scene=_SCENE, desc=True):
    return {"name": name, "scene": scene,
            "enemies": [_enemy("wader", desc and "A brine-bloated hulk trailing nets." or ""),
                        _enemy("archivist"),
                        _enemy("pale_eel"),
                        _enemy("tomekeeper")],
            # Generation requires per-party-size layouts (2x bodies per size).
            "layouts": {
                "1": ["wader", "archivist"],
                "2": ["wader", "archivist", "pale_eel", "tomekeeper"],
                "3": ["wader", "wader", "archivist", "pale_eel", "pale_eel",
                      "tomekeeper"],
                "4": ["wader", "wader", "archivist", "archivist", "pale_eel",
                      "pale_eel", "tomekeeper", "tomekeeper"],
            },
            "tokens": {}}


# --------------------------------------------------------------------------- #
# Persistence + API
# --------------------------------------------------------------------------- #
def test_scene_and_descriptions_persist_and_serve():
    meta = content.save_encounter(_encounter())
    path = content.CONTENT_DIR / f"{meta['id']}.json"
    try:
        on_disk = json.loads(path.read_text())
        assert on_disk["scene"] == _SCENE
        assert all(e["description"] for e in on_disk["enemies"])
        detail = content.encounter_detail(meta["id"])
        assert detail["scene"] == _SCENE
        assert detail["enemies"][1]["description"].startswith("A drowned scholar")
    finally:
        path.unlink(missing_ok=True)


def test_editor_shaped_save_round_trips_scene():
    """The editor posts {name, scene, enemies, tokens} with enemies spread from the
    loaded detail — scene and descriptions must survive an edit-save cycle."""
    meta = content.save_encounter(_encounter())
    path = content.CONTENT_DIR / f"{meta['id']}.json"
    try:
        detail = content.encounter_detail(meta["id"])
        edited = {"name": detail["name"], "scene": detail.get("scene", ""),
                  "enemies": [dict(e, hp=e["hp"] + 1) for e in detail["enemies"]],
                  "tokens": detail["tokens"]}
        content.save_encounter(edited, meta["id"])
        after = content.encounter_detail(meta["id"])
        assert after["scene"] == _SCENE
        assert all(e.get("description") for e in after["enemies"])
        assert after["enemies"][0]["hp"] == 9
    finally:
        path.unlink(missing_ok=True)


def test_hand_authored_encounters_default_to_empty_scene():
    detail = content.encounter_detail("builtin_a")
    assert detail["scene"] == ""


# --------------------------------------------------------------------------- #
# Generation: required, repaired when missing
# --------------------------------------------------------------------------- #
def test_generation_repairs_missing_scene_and_descriptions(monkeypatch):
    incomplete = _encounter(scene="")                      # no scene …
    incomplete["enemies"][2].pop("description")            # … one look missing
    complete = _encounter(name="Scene Repaired Zzz")
    replies = [json.dumps(incomplete), json.dumps(complete)]
    calls = []

    def fake_chat(api_key, model, messages):
        calls.append(messages[-1]["content"])
        return replies[len(calls) - 1]

    monkeypatch.setattr(llm, "_chat", fake_chat)
    monkeypatch.setattr(llm, "load_settings",
                        lambda: {**llm._default_settings(), "api_key": "sk"})
    meta = llm.generate_encounter(["soren", "ys"], "standard", "")
    path = content.CONTENT_DIR / f"{meta['id']}.json"
    try:
        assert len(calls) == 2                             # rejected, then repaired
        assert '"scene"' in calls[1] and '"description"' in calls[1]
        on_disk = json.loads(path.read_text())
        assert on_disk["scene"] and all(e["description"] for e in on_disk["enemies"])
    finally:
        path.unlink(missing_ok=True)


def test_prompt_teaches_scene_and_descriptions():
    D = llm.DEFAULT_INSTRUCTIONS
    for needle in ('"scene"', '"description"', "Scene & visual descriptions",
                   "battle backdrop", "physical appearance"):
        assert needle in D, needle
    # Every gold example models the pattern.
    assert D.count('"scene":"') == 3
    assert D.count('"description":"') >= 10